SIMS/views/admin_panel.py
from flask import Blueprint, redirect, request, render_template
from flask_login import login_required
from SIMS.models import School, Class, User

bp = Blueprint('admin_panel', __name__)

# 管理設定画面
@bp.route('/admin_panel', methods=['GET', 'POST'])
@login_required
def admin_panel():
    if request.method == 'GET':
        schools = School.get_all()
        classes = Class.get_all()
        users = User.get_all()
        return render_template('admin_panel.html', schools=schools, classes=classes, users=users)
    elif request.method == 'POST':
        type = request.form.get('type')
        pass

SIMS/views/login.py
from flask import Blueprint, redirect, render_template, request
from flask_login import current_user
from SIMS.user_auth import UserAuth

bp = Blueprint('login', __name__)

@bp.route('/login', methods=['GET', 'POST'])
def login():
    # ログイン済みの場合はトップページにリダイレクト
    if current_user.is_authenticated:
        return redirect('/')
    if request.method == 'POST':
        user_id = request.form.get('user_id')
        password = request.form.get('password')
         # user_idとpasswordが英数字かどうかチェック
        if not (user_id.isalnum() and password.isalnum()):
            return render_template('login.html', error_msg='パスワードは英数字のみで入力してください。')
        # IDとパスワードが一致したらトップページにリダイレクト
        if UserAuth.is_valid_user(user_id, password):
            UserAuth.login_user(user_id)
            return redirect('/')
        # 一致しなかったらログインページに戻る
        else:
            return render_template('login.html', error_msg='IDまたはパスワードが違います')
    else:
        return render_template('login.html', error_msg='')

SIMS/views/logout.py
from flask import Blueprint, redirect
from flask_login import login_required
from SIMS.user_auth import UserAuth

bp = Blueprint('logout', __name__)

@bp.route('/logout')
@login_required
def logout():
    # ログアウト処理
    UserAuth.logout_user()
    return redirect('/')

SIMS/views/school_list.py
from flask import Blueprint, render_template
from flask_login import login_required
from SIMS.models import School

bp = Blueprint('school_list', __name__)

@bp.route('/school_list')
@login_required
def school_list():
    schools = School.get_all()
    return render_template('school_list.html', schools=schools)

SIMS/views/student_detail.py
from os import name
from flask import Blueprint,app, render_template
from flask_login import login_required
from SIMS import app
from SIMS.models import School, Student

bp = Blueprint('student_detail', __name__)


# パスパラメータを使う(idの部分を変数に入れる)
@bp.route('/<school>/student_detail/<int:id>',methods=['GET', 'POST'])
@login_required

def student_detail(id,school):

    student = Student.get_one(id=id)
    schools = School.get_all()

    return render_template('student_detail.html',\
        student = student,\
        school = school,\
        schools = schools
    )  
 
    
if __name__ == '__main__':
    app.debug = True
    app.run(host='localhost')

SIMS/views/student_edit.py
from datetime import datetime
from os import name
from flask import Blueprint,app, jsonify, redirect, render_template, request, url_for
from flask_login import login_required
from SIMS import app
from SIMS.models import School, Student, Class

bp = Blueprint('student_edit', __name__)

# 生徒編集画面
@bp.route('/<school>/student_edit/<int:id>',methods=['GET', 'POST'])
@login_required

def student_edit(id,school):
    student = Student.get_one(id=id)
    schools = School.get_all()
    class_member = Class.get_all()
    
    status = request.form.get('student_delete')
    if request.method == 'POST':
        match status: 
            case None:
                student_update = Student.update(
                                id=request.form.get('id'),
                                name=request.form.get('name'),
                                name_kana=request.form.get('name_kana'),
                                school=school,
                                class_name=request.form.get('class_name'),
                                gender=int(request.form.get('gender')),                        
                                birthday=datetime.strptime(request.form.get('birthday'), '%Y-%m-%d'), # 文字列を日付型に変換
                                address=request.form.get('address'),
                                phone=request.form.get('phone'),
                                email=request.form.get('email'),
                                gmail=request.form.get('gmail'),
                                note=request.form.get('note'),
                                                )
                return redirect(url_for('student_list.student_list',school=school))
        
            case "delete" :
                student_delete = Student.delete(
                                id=request.form.get('id')
                                               )
                return redirect(url_for('student_list.student_list',school=school))
            
            case "list" :
                return redirect( url_for('student_list.student_list', school=school))

    if request.method == 'GET':
        return render_template('student_edit.html',\
        student = student,\
        school = school,\
        schools = schools,\
        class_member = class_member
            )  


if __name__ == '__main__':
    app.debug = True
    app.run(host='localhost')

SIMS/views/student_list.py
from flask import Blueprint, redirect, render_template
from flask_login import login_required
from SIMS.models import Student, School, Class

bp = Blueprint('student_list', __name__)

# 生徒一覧画面
@bp.route('/<school>/student_list')
@login_required
def student_list(school):
    # 生徒一覧を取得
    schools = School.get_all()
    categorized_students = Student.get_categorized_list(school)
    # 学校名が不正な場合はトップページにリダイレクト
    if school not in [school['name'] for school in schools]:
        return redirect('/')
    return render_template('student_list.html', categorized_students=categorized_students, schools=schools, school=school)

SIMS/views/student_register.py
from flask import Blueprint, render_template, request
from datetime import datetime
from SIMS.models import Student

bp = Blueprint('student_register', __name__)

# 生徒登録画面
@bp.route('/<school>/student_register/', methods=['GET', 'POST'])
def student_register(school):
    if request.method == 'POST':
        id= Student.add(
                    name=request.form.get('name'),
                    name_kana=request.form.get('name_kana'),
                    school=school,
                    class_name=request.form.get('class_name'),
                    gender=int(request.form.get('gender')),
                    birthday=datetime.strptime(request.form.get('birthday'), '%Y-%m-%d'), # 文字列を日付型に変換
                    address=request.form.get('address'),
                    phone=request.form.get('phone'),
                    email=request.form.get('email'),
                    gmail=request.form.get('gmail'),
                    note=request.form.get('note'),
                )
        student = Student.get_one(id=id)
        return render_template('student_detail.html',student=student ,school=school)
    else:
        return render_template('student_register.html',school=school)

SIMS/templates/admin_panel.html
<!-- SubTitleの設定 -->
{% set subTitle = '管理設定' %}

<!-- layoutの決定 -->
{% extends 'layout.html' %}

<!-- コンテンツ -->
{% block contents %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/admin_panel.css') }}"></link>
{{ super() }}
<div class="container">

    <h2>管理設定</h2>
    <p>ID: {{ current_user.get_one()['user_id'] }}</p>
    <!-- ユーザー一覧 -->
    <div class="row g-1 mt-3">
        <div class="col-auto">
            <h5 class="pt-1">ユーザー一覧</h5>
        </div>
    </div>
    <div class="row g-1">
        <table id="user-table" class="table table-striped table-hover mb-0">
            <thead>
                <tr>
                    <th>#</th>
                    <th>ユーザーID</th>
                    <th>操作</th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                    <tr>
                        <td>{{ user.id }}</td>
                        <td>{{ user.user_id }}</td>
                        <td>
                            {% set onclick = 'editUser(' ~ user.id ~ ',"' ~ user.user_id ~ '")' %}
                            <button class="btn btn-primary" name="edit-user" onclick="{{ onclick }}">編集</button>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3">
                        <button name="add-user" class="btn btn-primary" onclick="editUser()">ユーザー追加</button>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>

    <!-- 学校一覧 -->
    <div class="row g-1 mt-3">
        <div class="col-auto">
            <h5 class="pt-1">学校一覧</h5>
        </div>
    </div>
    <div class="row g-1">
        <table id="school-table" class="table table-striped table-hover mb-0">
            <thead>
                <tr>
                    <th>#</th>
                    <th>学校名</th>
                    <th>操作</th>
                </tr>
            </thead>
            <tbody>
                {% for school in schools %}
                    <tr>
                        <td>{{ school.id }}</td>
                        <td>{{ school.name }}</td>
                        <td>
                            {% set onclick = 'editSchool(' ~ school.id ~ ',"' ~ school.name ~ '")' %}
                            <button class="btn btn-primary" name="edit-school" onclick="{{ onclick }}">編集</button>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3">
                        <button name="add-school" class="btn btn-primary" onclick="editSchool()">学校追加</button>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>

    <!-- クラス一覧 -->
    <div class="row g-1 mt-3">
        <div class="col-auto">
            <h5 class="pt-1">クラス一覧</h5>
        </div>
    </div>
    <div class="row g-1">
        <table id="class-table" class="table table-striped table-hover mb-0">
            <thead>
                <tr>
                    <th>#</th>
                    <th>クラス名</th>
                    <th>操作</th>
                </tr>
            </thead>
            <tbody>
                {% for cls in classes %}
                    <tr>
                        <td>{{ cls.id }}</td>
                        <td>{{ cls.name }}</td>
                        <td>
                            {% set open_date = cls.open_date.strftime('%Y-%m-%d') %}
                            {% set close_date = cls.close_date.strftime('%Y-%m-%d') %}
                            {% set onclick = 'editClass(' ~ cls.id ~ ',"' ~ cls.name ~ '",' ~ cls.class_number ~ ',"' ~ open_date ~ '","' ~ close_date ~ '")' %}
                            <button class="btn btn-primary" name="edit-class" onclick="{{ onclick }}">編集</button>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3">
                        <button name="add-class" class="btn btn-primary" onclick="editClass()">クラス追加</button>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>
    
    <!-- モーダル -->
    <div class="modal fade" id="modal-main" tabindex="-1" aria-labelledby="modal-label-main" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="modal-label-main"></h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body"></div>
                <div class="modal-footer"></div>
            </div>
        </div>
    </div>

    <!-- サブモーダル -->
    <div class="modal fade" id="modal-sub" tabindex="-1" aria-labelledby="modal-label-sub" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="modal-label-sub"></h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body"></div>
                <div class="modal-footer"></div>
            </div>
        </div>
    </div>

    {{ '<script>{}</script>'.format('
        let schools = ' ~ schools | tojson ~ ';
        let classes = ' ~ classes | tojson ~ ';
        let users = ' ~ users | tojson ~ ';
    ') | safe }}
    <script src="{{ url_for('static', filename='js/admin_panel.js') }}"></script>
</div>
{% endblock %}

SIMS/templates/layout.html
{% set title = '生徒情報管理システム' %}

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}} - {{subTitle}}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"></link>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/common.css') }}"></link>
</head>
<body>
    {% block contents %}
    {% include 'navbar.html' %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

SIMS/templates/login.html
<!-- SubTitleの設定 -->
{% set subTitle = 'ログイン' %}

<!-- layoutの決定 -->
{% extends 'layout.html' %}

<!-- コンテンツ -->
{% block contents %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}"></link>
<div class="container">
    <h2 class="fw-bold">生徒管理ログインページ</h2>
    <p class="fs-6">IDとパスワードを入力して下さい</p>
    <form method="POST" id="loginForm">
        <label for="user_id" class="form-label">ID</label>
        <input type="text" class="form-control"  id="user_id" name="user_id" placeholder="ユーザー名" pattern="^[a-zA-Z0-9@\.-_]+$" minlength="4" maxlength="64" required>
        <label for="password" class="form-label">パスワード</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="パスワード" pattern="^[a-zA-Z0-9]+$" minlength="4" maxlength="64" required>
        <button type="submit" class="btn btn-primary" value="Submit">ログイン</button>
    </form>
{% if error_msg %}
<p style="color:red">{{ error_msg }}</p>
{% endif %}
    <!-- <p id="error"></p>
    <p id="error2"></p> -->
</div>
<script src="{{ url_for('static', filename='js/login.js') }}"></script>
{% endblock %}
</script>

</body>
</html>

SIMS/templates/navbar.html
<header class="container-fluid sticky-top border-bottom border-body bg-body-tertiary">
    <nav class="container-sm navbar navbar-expand-sm mx-auto flex-row justify-content-center" >
        <div>
            <a class="navbar-brand me-1" href="/">{{ title }}</a>
            <button class="navbar-toggler my-2" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent">
                <i class="fas fa-bars"></i>
            </button>
        </div>
        <div>
            <div class="collapse navbar-collapse row g-1" id="navbarContent">
                {% if school %} <!-- 学校選択時 -->
                    <div class="col-auto">
                        <span class="dropdown">
                            <button class="btn btn-outline-success dropdown-toggle" type="button" data-bs-toggle="dropdown">
                                {{ school }}
                            </button>
                            <ul class="dropdown-menu">
                                {% for s in schools %}
                                    <li><a class="dropdown-item" href="{{ url_for('student_list.student_list', school=s.name) }}">{{s.name}}</a></li>
                                {% endfor %}
                            </ul>
                        </span>
                    </div>
                {% endif %}
                {% if current_user.is_authenticated %} <!-- ログイン中の場合のみ表示 -->
                    <div class="col-auto">
                        {% set admin_panel = url_for('admin_panel.admin_panel') %}
                        <button class="btn btn-outline-primary" type="button" onclick="location.href='{{ admin_panel }}'">管理設定</button>
                        {% set logout = url_for('logout.logout') %}
                        <button class="btn btn-outline-secondary" type="button" onclick="location.href='{{ logout }}'">ログアウト</button>
                    </div>
                {% endif %}
            </div>
        </div>
    </nav>
    {% if studentSearch %} <!-- 生徒検索メニュー有効時 -->
        <nav class="container-sm navbar navbar-expand-md mx-auto flex-row justify-content-center" style="max-width: 960px;">
            <div>
                <div class="collapse navbar-collapse row g-1" id="studentSearch">
                    <div class="col-auto">
                        <input class="form-control" id="searchText" placeholder="検索文字列">
                    </div>
                    <div class="col-auto">
                        <select class="form-select" id="searchType">
                            <option value="all">検索対象:ALL</option>
                            <option value="name">名前</option>
                            <option value="name_kana">フリガナ</option>
                            <option value="gender">性別</option>
                            <option value="age">年齢</option>
                            <option value="school">学校名</option>
                            <option value="class_name">クラス</option>
                            <option value="address">住所</option>
                            <option value="phone">電話番号</option>
                            <option value="email">E-mail 個人用</option>
                            <option value="gmail">E-mail 学校用</option>
                            <option value="note">備考</option>
                        </select>
                    </div>
                    <div class="col-auto">
                        <button class="btn btn-outline-success" type="submit" id="studentSearchBtn">
                            <span class="d-none spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
                            <span>検索</span>
                        </button>
                    </div>
                    <div class="col-auto">
                        <input class="form-check-input" type="checkbox" value="" id="allSchoolSearch">
                        <label class="form-check-label" for="allSchoolSearch">全校検索</label>
                        <input class="form-check-input" type="checkbox" value="" id="graduated">
                        <label class="form-check-label" for="graduated">卒業生表示</label>
                    </div>
                </div>
                <div class="col-auto">
                    <button class="navbar-toggler my-2" type="button" data-bs-toggle="collapse" data-bs-target="#studentSearch">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </div>
            <div class="ms-auto">
                {% set student_register = url_for('student_register.student_register', school=school) %}
                <button class="btn btn-outline-primary" type="button" onclick="location.href='{{ student_register }}'">新規登録</button>
            </div>
        </nav>
    {% endif %}
</header>

SIMS/templates/school_list.html
<!-- SubTitleの設定 -->
{% set subTitle = '学校一覧' %}

<!-- layoutの決定 -->
{% extends 'layout.html' %}

<!-- コンテンツ -->
{% block contents %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/school_list.css') }}"></link>
{{ super() }}
<div class="container text-center">
    <h2 class="fw-bold">学校一覧</h2>
    <ul class="list-unstyled">
        {% for school in schools %}
        <li><a href="/{{ school.name }}/student_list">{{ school.name }}</a></li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

SIMS/templates/student_detail.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>生徒詳細</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/student_detail.css' ) }}">
</head>

<body>
    <header>
        <!-- SubTitleの設定 -->
        {% set subTitle = '生徒一覧' %}

        <!-- layoutの決定 -->
        {% extends 'layout.html' %}

        <!-- コンテンツ -->
        {% block contents %}
        <link rel="stylesheet" href="{{ url_for('static', filename='css/student_list.css') }}"></link>
        {{ super() }}

    

        <br><br>
        <div>
            <span><a href="{{student.next_id}}"><p>次へ</p></a></span>
            <span><a href="{{student.prev_id}}"><p>前へ</p></a></span>
        </div>
    </header>
    <main>
        <table class="table table-striped">
            <tr>
                <td>
                    id:{{student.id}}
                </td>
            </tr>
            <tr>
                <td>
                    生徒名：{{student.name}}
                </td>
            </tr>
            <tr>
                <td>
                    フリガナ：{{student.name_kana}}
                </td>
            </tr>
            <tr>
                <td>
                    クラス：{{student.class_name}}
                </td>
            </tr>
            <tr>
                <td>
                    性別：{{student.gender}}
                </td>
            </tr>
            <tr>
                <td>
                    生年月日：{{student.birthday}}
                </td>
            </tr>
            <tr>
                <td>
                    住所：{{student.address}}
                </td>
            </tr>
            <tr>
                <td>
                    電話番号：{{student.phone}}
                </td>
            </tr>
            <tr>
                <td>
                    E-mail 個人用：{{student.email}}
                </td>
            </tr>
            <tr>
                <td>
                    E-mail 学校用：{{student.gmail}}
                </td>
            </tr>
            <tr>
                <td>
                    備考：{{student.note}}
                </td>
            </tr>
        </table>
    </main>
    <footer>
        <p><a href="{{ url_for('student_edit.student_edit', id=student.id,school=school)}}">編集へ</a></p>
        <p><a href="{{ url_for('student_list.student_list', school=school)}}">生徒一覧へ</a></p>
    
        {% endblock %}

    <script src="../static/js/student_details.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>



</html>

SIMS/templates/student_edit.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>生徒編集</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/student_edit.css' ) }}">
</head>

<body>
    <header>
        <!-- SubTitleの設定 -->
        {% set subTitle = '生徒一覧' %}

        <!-- layoutの決定 -->
        {% extends 'layout.html' %}

        <!-- コンテンツ -->
        {% block contents %}
        <link rel="stylesheet" href="{{ url_for('static', filename='css/student_list.css') }}">
        </link>
        {{ super() }}


    </header>
    <main>
    <form method="post">
        <table class="table table-striped">
            <tr>
                <td>
                    id:<input type="text" name="id" value="{{student.id}}">
                </td>
            </tr>
            <tr>
                <td>
                    生徒名：<input type="text" name="name" value="{{student.name}}">
                </td>
            </tr>
            <tr>
                <td>
                    フリガナ：<input type="text" name="name_kana" value="{{student.name_kana}}">
                </td>
            </tr>
            <tr>
                <td>
                    クラス：
                    <select name="class_name">
                        {% for i in class_member %}
                        <option  {% if student.class_name == i.name %} selected {% endif %}>{{i.name}}</option>
                        {% endfor %}
                    </select>
                </td>
            </tr>
            <tr>
                <td>            
                    性別：  <input type="radio" name="gender" id="male" value="1" {% if student.gender == "男"%} checked{%endif%}>
                    <label for="male">男性</label>
                    <input type="radio" name="gender" id="female" value="2" {% if student.gender == "女"%} checked{%endif%}>
                    <label for="female">女性</label>
                </td>
            </tr>
            <tr>
                <td>
                    生年月日：<input type="text" name="birthday" value="{{student.birthday}}">
                </td>
            </tr>
            <tr>
                <td>
                    住所：<input type="text" name="address" value="{{student.address}}">
                </td>
            </tr>
            <tr>
                <td>
                    電話番号：<input type="text" name="phone" value="{{student.phone}}">
                </td>
            </tr>
            <tr>
                <td>
                    E-mail 個人用：<input type="text" name="email" value="{{student.email}}">
                </td>
            </tr>
            <tr>
                <td>
                    E-mail 学校用：<input type="text" name="gmail" value="{{student.gmail}}">
                </td>
            </tr>
            <tr>
                <td>
                    備考：<input type="text" name="note" value="{{student.note}}">
                </td>
            </tr>
        </table>
     </main>
     <footer>
        <p><button type="submit">生徒一覧へ</a></p></button>
        <p><button type="submit">更新</p></button>
    </form>
    <form method="post">
            <input type="hidden" name="student_delete" value="delete"><p><button type="submit">削除</p></button>
            <input type="hidden" name= "id" value="{{student.id}}">
    </form>
        <script src="../static/js/student_edit.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    
</body>

{% endblock %}

</html>

SIMS/templates/student_list.html
<!-- SubTitleの設定 -->
{% set subTitle = '生徒一覧' %}

{% set studentSearch = True %}

<!-- layoutの決定 -->
{% extends 'layout.html' %}

<!-- コンテンツ -->
{% block contents %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/student_list.css') }}"></link>
{{ super() }}
<div class="container">
    <!-- 生徒一覧 -->
    <h2>生徒一覧</h2>

    {% set gender = '男' %}
    {% set gender = 1 if gender == '男' else 2 %}
    {{gender}}
    <div id="student-list">
        {% for list in categorized_students if list.is_open %}
            {% if list.students|length > 0 %}
            <div class="row g-1 mt-3">
                <div class="col-auto">
                    <h5 class="pt-1">{{ school }} {{ list.class_number }} {{ list.class_name }}</h5>
                    <span>{{ list.open_date }} ～ {{ list.close_date }}</span>
                </div>
            </div>
            <div class="row g-1">
                <table id="student-table" class="table table-striped table-hover mb-0">
                    <thead>
                        <tr>
                            <th>名前</th>
                            <th>フリガナ</th>
                            <th>性別</th>
                            <th>年齢</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for student in list.students %}
                        {% set onclick_url = url_for('student_detail.student_detail', id=student.id, school=school) %}
                        <tr onclick="location.href = '{{ onclick_url }}'">
                            <td>{{ student.name }}</td>
                            <td>{{ student.name_kana }}</td>
                            <td>{{ student.gender }}</td>
                            <td>{{ student.age }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            {% endif %}
        {% endfor %}
    </div>
 
    {{ '<script>{}</script>'.format('
        let categorizedStudents = ' ~ categorized_students | tojson ~ ';
        let allStudents = null;
    ') | safe }}
    <script src="{{ url_for('static', filename='js/student_list.js') }}"></script>
</div>
{% endblock %}